spring:
  application:
    name: automating-devops
  data:
    mongodb:
      host: localhost
      port: 27017
      database: automating-devpos
      username: cagrikart@admin
      password: 676401
      uri: mongodb://localhost:27017/automating-devpos

server:
  port: 9091
  address: localhost

github:
  api:
    url: https://api.github.com
  owner: cagrikart

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org:
      springframework: INFO
    com:
      cagri: DEBUG 